import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const ROOT = process.cwd();
const OUTPUT = path.join(ROOT, "docs", "CODEMAP.md");
const START = "<!-- GENERATED-INVENTORY:START -->";
const END = "<!-- GENERATED-INVENTORY:END -->";
const ROOTS = ["src", "src-tauri/src", "scripts"];
const EXTENSIONS = new Set([".ts", ".tsx", ".rs", ".mjs"]);

async function collect(directory) {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const target = path.join(directory, entry.name);
      if (entry.isDirectory()) return collect(target);
      return EXTENSIONS.has(path.extname(entry.name)) ? [target] : [];
    }),
  );
  return nested.flat();
}

function summarize(file, source) {
  const firstComment = source
    .split(/\r?\n/)
    .map((line) => line.trim())
    .find((line) => line.startsWith("//") || line.startsWith("//!"));
  if (firstComment) return firstComment.replace(/^\/\/!?\s*/, "");
  const base = path.basename(file, path.extname(file));
  if (/\.test$/.test(base)) return "Tests for the adjacent module";
  if (/^[A-Z].*\.(tsx|ts)$/.test(path.basename(file))) return "React component or typed UI module";
  if (file.includes("src-tauri")) return "Rust backend module";
  if (file.includes("scripts")) return "Repository maintenance script";
  return "TypeScript application module";
}

const rows = [];
for (const root of ROOTS) {
  for (const file of await collect(path.join(ROOT, root))) {
    const source = await readFile(file, "utf8");
    rows.push({
      path: path.relative(ROOT, file).replaceAll(path.sep, "/"),
      lines: source.split(/\r?\n/).length,
      summary: summarize(file, source),
    });
  }
}
rows.sort((left, right) => left.path.localeCompare(right.path));

const generated = [
  START,
  "",
  "## Generated repository inventory",
  "",
  "> Generated by `npm run codemap`. Do not edit this section manually.",
  "",
  "| File | Lines | Responsibility |",
  "|---|---:|---|",
  ...rows.map(
    ({ path: file, lines, summary }) =>
      `| \`${file}\` | ${lines} | ${summary.replaceAll("|", "\\|")} |`,
  ),
  "",
  END,
].join("\n");

const current = await readFile(OUTPUT, "utf8");
let next;
if (current.includes(START) && current.includes(END)) {
  next = `${current.slice(0, current.indexOf(START))}${generated}${current.slice(current.indexOf(END) + END.length)}`;
} else {
  next = `${current.trimEnd()}\n\n${generated}\n`;
}

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error("docs/CODEMAP.md is stale. Run npm run codemap.");
    process.exit(1);
  }
  console.log("docs/CODEMAP.md is current.");
} else {
  await writeFile(OUTPUT, next, "utf8");
  console.log(`Updated docs/CODEMAP.md with ${rows.length} files.`);
}
